### PR TITLE
Fix build post monadfail proposal

### PR DESCRIPTION
**Pull request by alexfmpe**

### CODE REVIEW

**Review by nomeata — APPROVED** [review]

**Comment by alexfmpe** [comment]
Managed to build under 8.8 through 9.4 with this change.
This package is currently broken in nixpkgs, is there a way to get a new hackage release? 
https://hackage.haskell.org/package/free-theorems doesn't link to any repo and I haven't been able to contact the author - going by his thesis, the original author had it in darcs somewhere

**Comment by nomeata** [comment]
You refer to free-theorems itself, not the webui, right?

**Comment by alexfmpe** [comment]
> You refer to free-theorems itself, not the webui, right?

Ah yes

**Comment by nomeata** [comment]
Indeed, I have a darcs checkout from 2008 lying around here, but it’s even older than the 0.3.2.0 that I bundled in this repo.

If you really care you can try to contact Janis Voigtländer (<janis.voigtlaender@uni-due.de>) about this. Or I guess I could create a fresh git repo and ask the Hackage Trustees to be made uploader for this package…

**Comment by alexfmpe** [comment]
Hmm I seem to have confused the author and the maintainer listed in hackage and emailed both and on old addresses to boot.
@jvoigtlaender how do you think we should proceed here to propagate these fixes to hackage?

**Comment by nomeata** [comment]
Does GitHub reliably ping mentioned people on repos unrelated to them? I'm not sure. If he doesn't respond we'll have to try with his current email address.

**Comment by jvoigtlaender** [comment]
I don't think I have a repo copy of `free-theorems` anymore. I'm fine with Joachim creating a new repo from the old sources, and/or even with the repo history from his darcs checkout.

What do I need to do on the Hackage side to make this takeover possible?

Also, maybe @ichistmeinname should chime in. She has a renovated copy of `free-theorems` inside one of her project repos: https://github.com/ichistmeinname/free-theorems, so maybe Joachim's and Sandra's code changes should be merged?

**Comment by nomeata** [comment]
If Sandra touched it last maybe it's on her to take it over ;-)

**Comment by ichistmeinname** [comment]
Is this some kind of rule for open source? ; ) Not sure that I have the time to chip in.

Don’t you have students that might be up for such a task, Janis? I remember that the last version on my namespace, which is the result of a master’s thesis that I advised, still needs some polishing (e.g., error handling). I guess, I wouldn’t upload it to hackage in the current development state.

I’d be happy to add additional contributors / merge PRs though.

**Comment by nomeata** [comment]
Not a rule, just a cheap trick by me ;-)

I guess I can just take it over, if it's just keeping it compiling as dependencies change.

**Comment by nomeata** [comment]
> Indeed, I have a darcs checkout from 2008 lying around here, but it’s even older than the 0.3.2.0 that I bundled in this repo.

I stand corrected. That was just an import of the hackage release plus a few WIP patches of my own from back then.

I guess I’ll just start a fresh repo. Too bad that https://hdiff.luite.com/cgit/free-theorems/ no longer exists.

OH, and I just noticed I am still a maintainer for the hackage package. Ha! 
I just pushed a hackage release (https://hackage.haskell.org/package/free-theorems-0.3.2.1) from the code copy in this repo, to get @alexfmpe’s fixes out there. Maybe I’ll create a dedicated repository some other time.

**Comment by alexfmpe** [comment]
I now have a version of `free-theorems-static-webui` running locally that, like https://github.com/ichistmeinname/free-theorems, allows types of the form `(a -> b) -> f a -> f b`.
Started from the `free-theorems` at https://github.com/ichistmeinname/free-theorems, cherry-picked a few commits from the one here, then did some `haskell-src-exts` bumps to get it working for newer ghc. 
Mostly a mechanical process and I'm seeing some `Non-exhaustive patterns in case` errors coming from `free-theorems`, so it's not yet hackage-ready or anything.

Since there's no shared git history and the other repo has more work on its `free-theorems`, I'm thinking the easier path might be something like
1. PR the ecosystem bumps to https://github.com/ichistmeinname/free-theorems
2. Turn on unsafe warning/errors and fix those (e.g. non-exhaustive pattern matching)
3. Put the result on a dedicated repository
4. Upload to hackage

I _might_ be able to get 1 & 2 done during the holidays.

For reference, branch where I tested out the merge: https://github.com/alexfmpe/free-theorems-static-webui/commits/merge

**Comment by nomeata** [comment]
Great, thanks for taking that over!

I’d keep free-theorems-static-webui separate though, it is just a small GHCJS experiment of mine and doesn’t need the same level of attention as a library on hackage. I will drop the vendored copy in this repo and use the one from hackage again.

**Comment by jvoigtlaender** [comment]
That sounds like a good path forward. Thank you all!

**Pull request merged**
